Guard ssize_t redefinition to avoid MSVC error
Mitigates the MSVC error:
src\modbus-private.h(19): error C2632: 'int' followed by 'int' is
illegal

ssize_t is defined already on MSVC which causes the error

Signed-off-by: Uilian Ries <uilianries@gmail.com>